### PR TITLE
Optional vague event dupe checking

### LINKED ISSUE #68: Rapid fire supply rate notifications
Right now, supply rate notifications can fire every time `/runtriggers` is called, causing a lot of unnecessary notifications.  Dedupe doesn't catch it because the message is slightly changed (due to rate fluctuations).  Should alter these event objects so when dedupe checks them it doesn't see that rate part of the message so we shouldn't see these more than once per hour.

### PR DESCRIPTION
**Pull request by mikeshultz**
Will reduce rapid fire cToken supply rate notifications.

Closes #68

### CODE REVIEW

**Comment by DanielVF** [comment]
If the rate changes from 15% to 20%, we want to see it. This as written would block that?

**Comment by mikeshultz** [comment]
It would block that for an hour.  After an hour it'll fire again with the rate at the time.  I'm super skeptical seeing this every 5 minutes is any use and might actually cause some to mute the channel.  

Perhaps you want to watch a moving chart if you want live updates on this?

**Comment by DanielVF** [comment]
Perhaps let's just change the threshold to 18%. One notification moving in, and one moving out will okay.

**Comment by mikeshultz** [comment]
> One notification moving in, and one moving out will okay.

This would be the one moving in( with hourly updates).  Agreed that adding one moving out could be useful.  Would need to have some kind of toggle state storage for that.  Would want to separate that out into another issue.

**Comment by DanielVF** [comment]
I'm good with just the moving in one then. It's the important one for now.

**Pull request merged**
