### PR TITLE
Transaction harvesting from etherscan and fail transaction trigger

### PR DESCRIPTION
**Pull request by mikeshultz**
This uses Etherscan as a secondary source to ensure we have all relevant transactions in the DB(and not just ones that give us events).  This allows us to add a failed transaction trigger as well.

Right now this is only looking for failed transactions from OUSD token, Vault, and Timelock.  I didn't have strong reasoning for choosing these.  @DanielVF think this should be all the same contracts that we pull logs from?

### CODE REVIEW

**Comment by DanielVF** [comment]
These should be the only contracts we care about, yes!

**Review by DanielVF — APPROVED** [review]
Looks good. Love the fallback idea.

Will this have any problem starting up from a clean slate?

**Comment by mikeshultz** [comment]
> These should be the only contracts we care about, yes!

I mean, do we want this for all of them?

> Will this have any problem starting up from a clean slate?

Don't think so.  You see something concerning?  Data collection shouldn't be triggered until the first call of `/reload`

Though I did just find an unrelated error with this that I need to fix before rolling it.

**Comment by franckc** [comment]
@mikeshultz We should considering pull data for the new SingleAssetStaking.sol contract. And then later on (it is not deployed) from CompensationClaim.sol contract.

**Comment by mikeshultz** [comment]
> We should considering pulling data from the new SingleAssetStaking.sol contract. And then later on (it is not deployed yet) from CompensationClaim.sol contract.

Those contracts aren't in play yet, so not relevant to my question.  Looking to add the staking contract today.

**Comment by mikeshultz** [comment]
I added Timelock (thought it was already in).  If anyone feels strongly about pulling tx data from Etherscan for other contracts, we can add them later.

**Pull request merged**
