### PR TITLE
change multiplier calculation

### PR DESCRIPTION
**Pull request by rolandpo**
change multiplier calculation to ignore OETH held by the AMO

connected PR: https://github.com/OriginProtocol/oeth.com/pull/116

### CODE REVIEW

**Review by shahthepro — APPROVED** [review]
Looks good to me as well.

But one question, what do we do about the historical data in DB? Should we have a script to update those? Or is it fine if the new calculation is applied only for data fetched after this PR is deployed? cc @micahalcorn @rafaelugolini Thoughts?

**Comment by micahalcorn** [comment]
> Looks good to me as well.
> 
> But one question, what do we do about the historical data in DB? Should we have a script to update those? Or is it fine if the new calculation is applied only for data fetched after this PR is deployed? cc @micahalcorn @rafaelugolini Thoughts?

Thanks for asking 👍 It would be much better if the historical data is backfilled.

**Comment by shahthepro** [comment]
@rolandpo Do you wanna look into writing the backfill script?

**Comment by rolandpo** [comment]
there's already a backfilling script for OETH supply data is there not?
https://github.com/OriginProtocol/ousd-analytics/pull/366/files#diff-02d4da9db38e784299a3ee62ce70c15e65b434843b8ef6482719deb0e802dd7a

**Comment by shahthepro** [comment]
> there's already a backfilling script for OETH supply data is there not? https://github.com/OriginProtocol/ousd-analytics/pull/366/files#diff-02d4da9db38e784299a3ee62ce70c15e65b434843b8ef6482719deb0e802dd7a

Ah, my bad, I missed that. Let me try running this script locally and merge & deploy this PR. Thanks for your work :)

**Comment by shahthepro** [comment]
The script was a bit slower since the original intent of the script was completely different, I tweaked it to be only a couple of lines and a bit faster. Still it isn't as fast as I would like it to be.

One thing that stood out during my tests is that the PR desc and script update all mention just OETH. Why is it so? Shouldn't OUSD be also part of the script? Or is there anything I'm missing here?

**Comment by micahalcorn** [comment]
> The script was a bit slower since the original intent of the script was completely different, I tweaked it to be only a couple of lines and a bit faster. Still it isn't as fast as I would like it to be.
> 
> One thing that stood out during my tests is that the PR desc and script update all mention just OETH. Why is it so? Shouldn't OUSD be also part of the script? Or is there anything I'm missing here?

It would be good for OUSD to have the same logic.

**Comment by shahthepro** [comment]
I changed the script to be much more performant. I'm gonna merge and deploy this in a bit

**Pull request merged**
