### PR TITLE
Event ordering

### LINKED ISSUE #39: Trigger event ordering
The way the triggers are fired and events are ordered means that the events tend to be ordered by [trigger execution order], then [block number].  This causes events to be grouped by the trigger, which is generally not the same as execution on the blockchain.  

While this generally doesn't cause confusion since triggers are mostly separate concerns, sometimes they can describe contract interacting in a way that can be confusing.  For instance, if a governor contract accepts a proposal then executes a timelock transaction.  Events could be reversed showing the execution first.

Not a huge deal but giving events ordering data(block number and transaction index maybe) would help clarify these edge cases.

### PR DESCRIPTION
**Pull request by mikeshultz**
Adds event ordering by block number, tx index, and log index for events created by triggers.

Closes #39

### CODE REVIEW

**Comment by DanielVF** [comment]
Lot of duplicate code on those events.

Would it be possible to just say `ev=ev` on those individual events and have the event creation split them out automatically? Or just `, **ev_args(ev))` when creating the event, and use a helper method to create the args?

**Comment by mikeshultz** [comment]
Fair point.  I wasn't a huge fan of all the copy and pasting I had to do as well.  Though I'm not really sure I want the events code to be aware of those DB models, either.  Especially since not all of these events will be created from a `Log` model.

Could be worth adding an extra kwarg to those helper functions just for the `Log` model but not sure I want to go back and redo all these right this moment for that.  :shrug:

**Comment by DanielVF** [comment]
Now is probably the best time to redo those args to something simpler, because we sure won't feel like it the next time we add a just another event. Yeah, kwarg on the helper would be the best way.

**Comment by mikeshultz** [comment]
Done

**Pull request merged**
