### PR TITLE
add gtm

### PR DESCRIPTION
**Pull request by rolandpo**
add gtm, requires GOOGLE_TAG_ID env variable

### CODE REVIEW

**Comment by sparrowDom** [comment]
google tag ID is a public thing right @rolandpo? You can paste it here and I can add it to EnvKey

**Comment by jonathansnow** [comment]
**GTM ID**: GTM-K2LDMRW

**Comment by sparrowDom** [comment]
Added to EnvKey on production

**Comment by sparrowDom** [comment]
LGTM

**Review by sparrowDom — APPROVED** [review]

**Pull request merged**
